<?php
/*
Template Name: Map
*/
get_header(); ?>
<div class="map--container">
    <?php if (have_posts()) :
        while (have_posts()) : the_post(); ?>
            <article class="article" itemscope="itemscope" itemtype="http://schema.org/Article">
                <header class="article--header">
                    <h2 class="article--headline" itemprop="headline"><?php the_title(); ?></h2>
                </header>
                <div class="grap">
                    <?php the_content(); ?>
                </div>
                <div class="footer-map-note">
                    <p>点击浮标可查看相关游记。</p>
                    <p>灰色浮标代表已去过但没有相关游记。</p>
                    <p>Map generated by <a href="https://fatesinger.com/100405" target="_blank" title="WordPress 插件Marker Pro" class="cute">Marker Pro</a>.</p>
                </div>
            </article>
    <?php endwhile;
    // get_template_part('template-parts/pagination');
    endif; ?>
    <div class="back">
        <a href="<?php echo home_url(); ?>">返回首页</a>
    </div>
</div>
<?php get_footer(); ?>